[package]
name = "rust_ca"
version = "0.1.0"
authors = ["hugcis <hmj.cisneros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
gif = "0.11.1"
rand = "0.8.2"
flate2 = "1.0.19"